export const so = {
  nav: {
    home: "Hoyga",
    howToPlay: "Sida Loo Ciyaaro",
    challenges: "Caqabadaha",
    play: "Ciyaar",
  },
  hero: {
    badge: "Ciyaarta Xafladda ee Ugu Fiican",
    title1: "Wareejin iyo",
    title2: "Dhibaato",
    subtitle: "Wareejin gaariga. Aqbal qaddaadkaaga. Naxariis ma jirto, baxsasho ma jirto.",
    startPlaying: "Bilow Ciyaarta",
    howItWorks: "Sida Ay U Shaqeyso",
    players: "2–10 Ciyaaryahan",
    instantChaos: "Kheylaad Degdeg ah",
    oneSurvivor: "Mid Baxshay",
    spinBtn: "WAREEJIN GAARIGA",
    spinning: "Wareejinaya...",
    challengeLabel: "CAQABADAADA",
  },
  howToPlay: {
    heading: "Sida Loo Ciyaaro",
    subheading: "5 xeer fudud. Dhibaato xad-dhaaf ah.",
    legend: "Heer-sarrayntaadu",
    legendSub: "halkan bay bilaabataa.",
    rules: [
      {
        num: "01",
        title: "Wareejin Gaariga",
        body: "Ciyaaryahan kasta wuxuu wareejiyaa marka. Waxay ku soo degto — taasi waa qaddaadkaaga. Oohin la ma oggola.",
      },
      {
        num: "02",
        title: "Aqbal Qaddaadkaaga",
        body: "Dhammee caqabadaada ama wajah ciqaab kooxdu u codeysay. Gaariga ma xagoodsado.",
      },
      {
        num: "03",
        title: "Dacwee Khiyaanada",
        body: "Haddii qof diido caqabaddiisa, kooxdu waxay u codeysaa ciqaab laba jeer ah. Dimuqraadiyad xagga ugu fiican.",
      },
      {
        num: "04",
        title: "Kan Ugu Dambeeya ee Taagan",
        body: "Ciyaaryahanka ugu horreeya ee ka baxo saddex caqabad ayaa ka saara. Sii wareejin ilaa mid jabariiro.",
      },
      {
        num: "05",
        title: "Taaj Ku Cas Gaalibka",
        body: "Badbaadiyaha ugu dambeeya wuxuu dooranayaa ciqaabta ugu dambeysa ee kuwa kale. Guul macaan, macaan.",
      },
    ],
  },
  challenges: {
    heading: "Gaariga",
    subheading: "8 qaddaad. Mid kaliya ayaa naxariista.",
    items: [
      { label: "DHAQDHAQAAQ", text: "60 ilbiriqsi, joojin ma jirto" },
      { label: "DHAB", text: "Sheeg sirta ugu weyn" },
      { label: "DAREEN", text: "Kooxdu go'aanka ku qabto" },
      { label: "DHIBAATO", text: "Wareejin mar labaad — laba jeer ama waxba" },
      { label: "GEESI", text: "Samee 20 taallo 30 ilbiriqsi" },
      { label: "GUROW", text: "Nasiib wanaag... mar kasta" },
      { label: "SHURUUC", text: "Siiy caqabadaada qof kasta" },
      { label: "CABASHO", text: "Cab, bahane ma jirto" },
    ],
  },
  cta: {
    heading: "Diyaar u tahay Dhibaatada?",
    sub: "Uruuri asxaabtaada. Isku diyaari. Wareejin.",
    btn: "Ciyaar Hadda — Bilaash ah",
  },
  footer: {
    tagline: "Wareejin gaariga. Badbaado ciyaarta.",
    home: "Hoyga",
    about: "Ku Saabsan",
    contact: "Xiriir",
    viewSource: "Eeg Xogta",
    madeWith: "Sameysan",
    by: "Mustafa",
    suffix: "Naxariis ma jirto ku libaaxa sharafta.",
  },
};

export const ar = {
  nav: {
    home: "الرئيسية",
    howToPlay: "كيف تلعب",
    challenges: "التحديات",
    play: "العب",
  },
  hero: {
    badge: "أفضل لعبة حفلات على الإطلاق",
    title1: "أدر و",
    title2: "عاني",
    subtitle: "أدر العجلة. اقبل مصيرك. لا رحمة، لا هروب.",
    startPlaying: "ابدأ اللعب",
    howItWorks: "كيف تعمل",
    players: "٢–١٠ لاعبين",
    instantChaos: "فوضى فورية",
    oneSurvivor: "ناجٍ واحد",
    spinBtn: "أدر العجلة",
    spinning: "جارٍ الدوران...",
    challengeLabel: "تحديك",
  },
  howToPlay: {
    heading: "كيف تلعب",
    subheading: "٥ قواعد بسيطة. معاناة لا نهاية لها.",
    legend: "أسطورتك",
    legendSub: "تبدأ هنا.",
    rules: [
      {
        num: "٠١",
        title: "أدر العجلة",
        body: "كل لاعب يأخذ دوره في الإدارة. أينما توقفت — هذا هو مصيرك. البكاء ممنوع.",
      },
      {
        num: "٠٢",
        title: "اقبل مصيرك",
        body: "أكمل تحديك أو واجه عقوبة يختارها المجموعة. العجلة لا تتفاوض.",
      },
      {
        num: "٠٣",
        title: "كشف الغشاشين",
        body: "إذا رفض أحدهم تحديه، تصوّت المجموعة على عقوبة مضاعفة. الديمقراطية في أبهى صورها.",
      },
      {
        num: "٠٤",
        title: "آخر من يصمد",
        body: "أول لاعب يرفض ثلاثة تحديات يُستبعد. استمر بالدوران حتى يبقى بطل واحد.",
      },
      {
        num: "٠٥",
        title: "توّج الفائز",
        body: "الناجي الأخير يختار العقوبة النهائية للجميع. حلاوة النصر المطلقة.",
      },
    ],
  },
  challenges: {
    heading: "العجلة",
    subheading: "٨ أقدار. واحد فقط رحيم.",
    items: [
      { label: "ارقص", text: "٦٠ ثانية، لا توقف" },
      { label: "الحقيقة", text: "اكشف سرك الأكبر" },
      { label: "بري", text: "المجموعة تقرر مصيرك" },
      { label: "عانِ", text: "أدر مرة أخرى — ضعف أو لا شيء" },
      { label: "تحدٍ", text: "اعمل ٢٠ تمرين ضغط في ٣٠ ثانية" },
      { label: "تخطَّ", text: "حظك معك... هذه المرة" },
      { label: "مرّر", text: "أعطِ تحديك لأي شخص" },
      { label: "اشرب", text: "احتسِ، لا أعذار" },
    ],
  },
  cta: {
    heading: "مستعد للمعاناة؟",
    sub: "اجمع أصدقاءك. استعد. أدر.",
    btn: "العب الآن — مجاناً",
  },
  footer: {
    tagline: "أدر العجلة. انجُ من اللعبة.",
    home: "الرئيسية",
    about: "عن اللعبة",
    contact: "تواصل",
    viewSource: "عرض الكود",
    madeWith: "صُنع بـ",
    by: "مصطفى",
    suffix: "لا استرداد للكرامة المفقودة.",
  },
};

export const en = {
  nav: {
    home: "Home",
    howToPlay: "How to Play",
    challenges: "Challenges",
    play: "Play",
  },
  hero: {
    badge: "The Ultimate Party Chaos Game",
    title1: "Spin &",
    title2: "Suffer",
    subtitle: "Spin the wheel. Accept your fate. No mercy, no escapes.",
    startPlaying: "Start Playing",
    howItWorks: "How It Works",
    players: "2–10 Players",
    instantChaos: "Instant Chaos",
    oneSurvivor: "One Survivor",
    spinBtn: "SPIN THE WHEEL",
    spinning: "Spinning...",
    challengeLabel: "YOUR CHALLENGE",
  },
  howToPlay: {
    heading: "How to Play",
    subheading: "5 simple rules. Infinite suffering.",
    legend: "Your legend",
    legendSub: "begins here.",
    rules: [
      {
        num: "01",
        title: "Spin the Wheel",
        body: "Every player takes a turn spinning. Whatever it lands on — that's your fate. No crying allowed.",
      },
      {
        num: "02",
        title: "Accept Your Fate",
        body: "Complete your challenge or face a group-voted punishment. The wheel does not negotiate.",
      },
      {
        num: "03",
        title: "Call Out Cheaters",
        body: "If someone refuses their challenge, the group votes on a double punishment. Democracy at its finest.",
      },
      {
        num: "04",
        title: "Last One Standing",
        body: "First player to bail on three challenges is eliminated. Keep spinning until one legend remains.",
      },
      {
        num: "05",
        title: "Crown the Winner",
        body: "The last survivor picks the final punishment for everyone else. Sweet, sweet victory.",
      },
    ],
  },
  challenges: {
    heading: "The Wheel",
    subheading: "8 fates. Only one is kind.",
    items: [
      { label: "DANCE", text: "60 seconds, no stopping" },
      { label: "TRUTH", text: "Reveal your biggest secret" },
      { label: "WILD", text: "The group decides your fate" },
      { label: "SUFFER", text: "Spin again — double or nothing" },
      { label: "DARE", text: "Do 20 push-ups in 30 seconds" },
      { label: "SKIP", text: "Lucky you… this time" },
      { label: "PASS", text: "Give your challenge to anyone" },
      { label: "DRINK", text: "Take a sip, no excuses" },
    ],
  },
  cta: {
    heading: "Ready to Suffer?",
    sub: "Gather your friends. Brace yourselves. Spin.",
    btn: "Play Now — It's Free",
  },
  footer: {
    tagline: "Spin the wheel. Survive the game.",
    home: "Home",
    about: "About",
    contact: "Contact",
    viewSource: "View Source",
    madeWith: "Made with",
    by: "Mustafa",
    suffix: "No refunds on dignity.",
  },
};